Update main1.yml

diff --git a/.github/workflows/main1.yml b/.github/workflows/main1.yml
--- a/.github/workflows/main1.yml
+++ b/.github/workflows/main1.yml
@@ -16,13 +16,14 @@ env:
   DEPLOYMENT_NAME: my-deployment
   POD_NAME: my-pod
   SECRET_ID: ${{ secrets.SECRET_ID }}  # ID of the secret in IBM Cloud Secrets Manager
-  SECRETS_MANAGER_URL: ${{ secrets.SECCRETS_MANAGER_URL }}  # URL of the Secrets Manager instance
+  # Manually set your SECRETS_MANAGER_URL here
+  SECRETS_MANAGER_URL: "https://caa65fc7-ea5b-4f4b-be25-af98144cc5e5.us-south.secrets-manager.appdomain.cloud"
 
 jobs:
   setup-build-publish-deploy:
     name: Setup, Build, Publish, and Deploy
     runs-on: ubuntu-latest
-    environment: production
+	environment: production
     steps:
 
     - name: Checkout
@@ -71,29 +72,33 @@ jobs:
     # Retrieve secrets from IBM Cloud Secrets Manager
     - name: Retrieve secrets from IBM Cloud Secrets Manager
       id: retrieve-secrets
-      env:
-        SECRETS_MANAGER_URL: ${{ secrets.SECCRETS_MANAGER_URL }}
       run: |
         echo "Retrieving secret with ID: $SECRET_ID from URL: $SECRETS_MANAGER_URL"
         SECRET=$(ibmcloud secrets-manager secret --id $SECRET_ID --service-url $SECRETS_MANAGER_URL --output json || echo "Failed to retrieve secret")
         echo "Secret fetched: $SECRET"
-        if [[ $SECRET == "Failed to retrieve secret" ]]; then
-          echo "Error retrieving secret"
+        if echo "$SECRET" | jq .; then
+          echo "Valid JSON received"
+          echo "::set-output name=secret::$SECRET"
+        else
+          echo "Error retrieving secret or invalid JSON"
           exit 1
         fi
-        echo "::set-output name=secret::$SECRET"
-        
+
     # Parse the secrets and create Kubernetes secret
     - name: Parse secrets and create Kubernetes secret
       run: |
         echo "Parsing the retrieved secret..."
-        SECRET=${{ steps.retrieve-secrets.outputs.secret }}
+        SECRET="${{ steps.retrieve-secrets.outputs.secret }}"
         echo "Retrieved Secret JSON: $SECRET"
-        USERNAME=$(echo $SECRET | jq -r '.resources[0].username')
-        PASSWORD=$(echo $SECRET | jq -r '.resources[0].password')
+        USERNAME=$(echo "$SECRET" | jq -r '.username')
+        PASSWORD=$(echo "$SECRET" | jq -r '.password')
+        if [ -z "$USERNAME" ] || [ -z "$PASSWORD" ]; then
+          echo "Error: Username or Password not found in the secret"
+          exit 1
+        fi
         echo "Username: $USERNAME"
         echo "Password: $PASSWORD"
-        kubectl create secret generic my-k8s-secret --from-literal=username=$USERNAME --from-literal=password=$PASSWORD --namespace=default --dry-run=client -o yaml | kubectl apply -f -
+        kubectl create secret generic my-k8s-secret --from-literal=username="$USERNAME" --from-literal=password="$PASSWORD" --namespace=default --dry-run=client -o yaml | kubectl apply -f -
 
     # Configure kubectl to use the IKS cluster
     - name: Configure kubectl
