Update main1.yml

diff --git a/.github/workflows/main1.yml b/.github/workflows/main1.yml
--- a/.github/workflows/main1.yml
+++ b/.github/workflows/main1.yml
@@ -78,11 +78,17 @@ jobs:
         echo "USERNAME=${username}" >> $GITHUB_ENV
         echo "PASSWORD=${password}" >> $GITHUB_ENV
 
-    # Debugging output before creating secret
-    - name: Debugging output before creating secret
+     - name: Debugging output before creating secret
       run: |
-        echo "Username to be stored in secret: ${{ env.USERNAME }}"
-        echo "Password to be stored in secret: ${{ env.PASSWORD }}"
+        escaped_password=$(echo '3fr"'\''t^nXbt;UUi' | sed "s/\"/\\\\\"/g")
+        printf "Username to be stored in secret: %s\n" "${{ env.USERNAME }}"
+        printf "Password to be stored in secret: %s\n" "$escaped_password"
+    
+        if [[ -z "${{ env.USERNAME }}" || -z "$escaped_password" ]]; then
+          echo "Error: Username or password environment variable is empty."
+          exit 1
+        fi
+
 
     # Create Kubernetes secret
     - name: Create Kubernetes secret
